fix(deps): Revert zip to 2.2 to fix lzma-rust2/crc incompatibility
Dependabot PR #24 updated zip from 2.2 to 7.1, which pulls in lzma-rust2
0.15.3. This version has an incompatible crc API that causes build failures:

  error[E0107]: struct takes 1 generic argument but 2 generic arguments

Reverting to zip 2.2 resolves the compilation issue.